//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_id { get; set; }
        public string Employee_Name { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string ProfilePhoto { get; set; }
    }
}
